run:
  # do not run on test files yet
  tests: false

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  lll:
    line-length: 100
    tab-width: 4

  prealloc:
    simple: false
    range-loops: false
    for-loops: false

  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    - megacheck
    - govet
  disable:
    - maligned
    - prealloc
  disable-all: false
  presets:
    - bugs
    - unused
  fast: false
