openapi: 3.0.0
servers:
  - url: "http://localhost:3000"
info:
  title: WASAText
  description: WASAText, the skeleton project for Web and Software architecture course
  version: 1.0.0

tags:
  - name: "User"
    description: endpoints for users related operations
  - name: "Conversations"
    description: endpoints for conversation related operations
  - name: "Login"
    description: enpoints for loggin in action
  - name: "Photo"
    description: endpoints for photo related operations
  - name: "Message"
    description: endpoints for message related operations
  - name: "Group"
    description: endpoints for group related operations
  - name: "Like"
    description: endpoints for like related operations
  - name: "Comment"
    description: endpoints for comment related operations
  
  
paths:




  /groups/{groupId}/photo:
    put:
      security:
        - bearerAuth: []
      tags:
        -Group
        -Photo
      summary: sets the photo of the group
      description: |-
        sets the photo that
        the group will be seen with
      parameters:
        
        - $ref: "#/components/parameters/groupId"

      operationId: setGroupPhoto
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [photoUrl]
              properties:
                photoUrl:
                  type: string
                  format: uri
                  minLength: 10
                  maxLength: 2048
                  pattern: '^https?://.*$'
                  description: New photo URL for the Group
      responses:
        "204":
          description: group photo updated succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"

    
  /groups/{groupId}:


    put:
      security:
        - bearerAuth: []
      tags:
        -Group
      summary: sets the name of the group
      description: |-
        sets the name that
        the group will be seen with
      parameters:

        - $ref: "#/components/parameters/groupId"

      operationId: setGroupName
      requestBody:
        content:
          application/json:
            schema:
              $ref: "components/schemas/Group/GroupName"
      responses:
        "204":
          description: group name updated succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"

    post:
      security:
        -bearerAuth: []
      tags:
        -Group
      summary: creates a new group
      description: |-
        creates a new object
        group with one or more users
      parameters:

        - $ref: "#/components/parameters/groupId"

      operationId: createGroup
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Group"
      responses:
        "201":
          description: group created succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users/{userId}/group/{groupId}:

    delete:
      security:
        -bearerAuth: []
      tags:
        -Group
      summary: removes a user from a group
      description: |-
        removes the group from
        the user conversations
      parameters:

        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/groupId"
        
      operationId: deleteGroup
      responses:
        "204":
          description: group removed succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"

      post:
        security:
      -bearerAuth: []
        tags:
          -Group
        summary: add a user to a group
        description: |-
          creates a new object
          user in an existent group
        parameters:

          - $ref: "#/components/parameters/userId"
          - $ref: "#/components/parameters/groupId"
        
        operationId: addToGroup
        responses:
          "201":
            description: group created succesfully
          "400":
            $ref: "#/components/responses/BadRequest"
          "403":
            $ref: "#/components/responses/Forbidden"
          "500":
            $ref: "#/components/responses/InternalServerError"


  /users/{userId}/conversations/{conversationId}/messages:

    post:
      security:
        -bearerAuth: []
      tags:
        -Message
      summary: creates a message in a conversation
      description: |-
        sends a message to a user
        or a group conversation
      parameters:

        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/conversationId"

      operationId: sendMessage
      requestBody:
        content:
          application/json: 
            schema:
              $ref: "#/components/schemas/Message" 
      responses:
        "201":
          description: message created succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"


  /users/{userId}/conversations/{conversationId}/messages/{messageId}:

    delete:
      security:
        -bearerAuth: []
      tags:
        -Message
      summary: deletes a message
      description: |-
        removes a message 
        of a specific user
      parameters:

        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/messageId"
        - $ref: "#/components/parameters/conversationId"
        
      operationId: deleteMessage
      responses:
        "204":
          description: message removed succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"
        
    put:
      security:
        -bearerAuth: []
      tags:
        -Message
      summary: forwards a message in another conversation
      description: |-
        sends a message already existent
        to another conversation
      parameters:

        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/messageId"
        
      operationId: forwardMessage
      requestBody:
        content:
          application/json: 
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        "201":
          description: message forwarded succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"


    
  /users/{userId}/messages/{messageId}comments:

    post:
      security:
        -bearerAuth: []
      tags:
        -Comment
        -Message
      summary: comments a message
      description: |-
        add a comment to a 
        message of a specific user
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/messageId"

      operationId: commentMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Comment"
      responses:
        "201":
          description: comment created succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users/{userId}/messages/{messageId}comments/{commentId}:

    delete:
      security:
        -bearerAuth: []
      tags:
        -Comment
        -Message
      summary: deletes a comment
      description: |-
        removes a comment to a 
        message of a specific user
      parameters:

        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/messageId
        - $ref: "#/components/parameters/commentId"

      operationId: uncommentMessage
      responses:
        "204":
          description: comment removed succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users/{userId}/conversations:
    get:
      security:
        -bearerAuth: []
      tags:
        -Conversations
      summary: returns all the conversations
      description: |-
        returns personal stream of conversations
        for the user
      parameters:

          - $ref: "#/components/parameters/userId"

      operationId: getMyConversations
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConversationList"
            
      responses:
        "200":
          description: conversations retrieved succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"
    
  /users/{userId}/conversations/{conversationId}:
    get:
      security:
        -bearerAuth: []
        tags:
          -Conversations
        summary: returns a specific conversation
        description: |-
          finds a specific conversation
          from its id
        parameters:

          - $ref: "#/components/parameters/conversationId"
          - $ref: "#/components/parameters/userId"

        operationId: getConversation
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conversations"
        responses:
        "200":
          description: conversation retrieved succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"

    post:
      security:
        -bearerAuth: []
      tags:
        -Conversation
      summary: creates a new conversation
      description: |-
        generates a new conversation
        between two users
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/conversationId"

      operationId: createConversation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Conversation"
      responses:
        "201":
          description: conversation created succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"
              


  /login:
    post:
      security:
        - bearerAuth: []
      tags:
        - Login
      summary: logs in the  user
      description: |-
        if the user does not exist it will be created
        else it will be logged in; either way the userId is returned
      operationId: doLogin
      requestBody:
        description: Username to be used for loggin in
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User/Username"

        required: true

      responses:
        "201":
          description: user log in action succesful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

        "400":
          $ref: "#/components/responses/BadRequest"

        "403":
          $ref: "#/components/responses/Forbidden"

        "500":
          $ref: "#/components/responses/InternalServerError"

          
  /users/{userId}:
    put:
      security:
        - bearerAuth: []
      tags:
        -User
      summary: sets the name of the user
      description: |-
        sets the name that
        the user will be seen with
      parameters:

        - $ref: "#/components/parameters/userId"

      operationId: setMyUsername
      requestBody:
        description: creates/changes your own username
        content:
          application/json:
            schema:
              $ref: "components/schemas/User/Username"
      responses:
        "204":
          description: username updated succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users/{userId}/photo:
    put:
      security:
        - bearerAuth: []
      tags:
        -User
        -Photo
      summary: sets the photo of the user
      description: |-
        sets the photo that
        the user will be seen with
      parameters:

        - $ref: "#/components/parameters/userId"
        
      operationId: setMyPhoto
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [photoUrl]
              properties:
                photoUrl:
                  type: string
                  format: uri
                  minLength: 10
                  maxLength: 2048
                  pattern: '^https?://.*$'
                  description: New photo URL for the user
      responses:
        "204":
          description: user photo updated succesfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:

  parameters:

    userId:
      description: identifier for a single user
      schema:
        $ref: "#/components/schemas/Identifier"
      name: userId
      in: path
      required: true

    messageId:
      description: identifier for a single message
      schema:
        $ref: "#/components/schemas/Identifier"
      name: messageId
      in: path
      required: true

    commentId:
      description: identifier for a single comment
      schema:
        $ref: "#/components/schemas/Identifier"
      name: commentId
      in: path
      required: true

    groupId:
      description: identifier for a single group
      schema:
        $ref: "#/components/schemas/Identifier"
      name: groupId
      in: path
      required: true

    conversationId:
      description: identifier for a single conversation
      schema:
        $ref: "#/components/schemas/Identifier"
      name: conversationId
      in: path
      required: true

  responses:
    
      BadRequest:
        description: syntax of the request was not compliant with docs, check parameters
    
      Forbidden:
        description: server will not accept request due to lacking of client permissions
    
      NotFound:
        description: resource not found

      InternalServerError:
        description: the server encountered an error while processing the request


  schemas:

    Identifier:
      title: identifier
      description: alphanumerical identifier for a resource
      type: string
      pattern: "^@[A-Z][0-9]{9}$"
      example: "@U000000001"
      readOnly: true
      minLength: 11
      maxLength: 11

    User:
      title: user
      description: local user
      type: object
      properties:
        Username:
          type: string
          example: filippohd
          pattern: "^[a-z0-9]*?$"
          minLength: 1
          maxLength: 12
        UserId:
          $ref: "#/components/schemas/Identifier"

    Message:
      title: message
      description: message of a user in a conversation
      type: object
      properties:
        MessageBody: 
          type: string
          example: ciao
          pattern: "^[a-z0-9]*?$"
          minLenght: 1
          maxLenght: 50
        Comments:
          type: array
          items:
            $ref: "#/components/schemas/Comment"
        UploaderId:
          $ref: "#/components/schemas/Identifier"
        MessageId:
          $ref: "#/components/schemas/Identifier"
        Date:
          type: string
          format: date-time
          pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$"
          example: "2021-05-12T09:00:00Z"
          minLength: 20
          maxLength: 20
        MediaType:
          type: string
          enum: [text, photo]
          description: Type of media in the message

    Comment:
      title: comment
      description: comment of a message
      type: object
      properties:
        CommentId:
          $ref: "#/components/schemas/Identifier"
        MessageId:
          $ref: "#/components/schemas/Identifier"
        CommentBody:
          type: string
          example: ciao
          pattern: "^[a-z0-9]*?$"
          minLenght: 1
          maxLenght: 50
        Date:
          type: string
          format: date-time
          pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$"
          example: "2021-05-12T09:00:00Z"
          minLength: 20
          maxLength: 20
        UploaderId:
          $ref: "#/components/schemas/Identifier"
    
    Group:
      title: group
      description: group conversation of multiple users
      type: object
      properties:
        GroupId:
          $ref: "#/components/schemas/Identifier"
        GroupName:
          type: string
          example: gruppohd
          pattern: "^[a-z0-9]*?$"
          minLength: 1
          maxLength: 12
        Users:
          type: array
          items:
            $ref: "#/components/schemas/User"
        Messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
        

    Conversation:
      title: conversation
      description: conversation on the platform
      type: object
      properties:
        ConversationId:
          $ref: "#/components/schemas/Identifier"
        UserConnected:
          $ref: "#/components/schemas/Identifier"
        UserHosting:
          $ref: "#/components/schemas/Identifier"
        ChatName:    
          type: string
          description: the name of the conversation is the same as the user connected
          example: gruppohd
          pattern: "^[a-z0-9]*?$"
          minLength: 1
          maxLength: 12 

            
